"""add_team_id_to_tasks

Revision ID: a5e02b8c330f
Revises: 604a72d89134
Create Date: 2026-02-20 06:31:42.232671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5e02b8c330f"
down_revision: Union[str, Sequence[str], None] = "604a72d89134"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("team_id", sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key(None, "tasks", "teams", ["team_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tasks_team_id_teams", "tasks", type_="foreignkey")
    op.drop_column("tasks", "team_id")
    # ### end Alembic commands ###
